server:
  port: 7777
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
zuul:
  routes:
    eureka-client: # 这里配的是服务名
      path: /api-a/** # ，最后访问时地址就是: {ip}:{port}/api-a/**这里是通过zuul调用上面服务的地址
  prefix: /proxy # 添加前缀
  sensitive-headers: Cookie,Set-Cookie,Authorization # 配置不进行过滤的host头信息(zuul默认会过滤掉一些敏感的头信息，包括下面三个)
  add-host-header: true #设置为true重定向是会添加host请求头
  retryable: true # 关闭重试机制
  AccessFilter: #控制是否启用指定过滤器
    pre:
      disable: false #true表示关闭

# 开启通过url查看路由信息，简单信息：{ip}:{port}/actuator/routes，详细信息：{ip}:{port}/actuator/routes/details
management:
  endpoints:
    web:
      exposure:
        include: 'routes'

ribbon:
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 1000
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 3000

