server:
  port: 7003

spring:
  application:
    name: eureka-security
  security:
    user:
      # 配置spring security登录用户名和密码
      name: user
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
