server:
  port: 7788

spring:
  redis:
    host: localhost
    port: 6379
    lettuce: # lettuce版本的连接redis的java client
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1 # 连接池最大阻塞等待时间，-1表示无限制
        max-idle: 8 # 连接池中最大空连接数
        min-idle: 0 # 连接池中最小空连接数

subscribe:
  url: test
